"""Bridge between the legacy ``targets/<name>/`` working folders and the governed
``runs/`` control-plane.

Two directions:

* **import** (targets -> run): copy a legacy target workspace's files into a
  governed run's ``artifacts/imported/`` tree and register each as evidence
  (hash + size). No parsing, no fabricated findings — the operator supplies the
  governed metadata (target, scope, authorization) and promotes findings by hand.
* **materialize** (run -> targets): render a read-only, regenerable markdown
  working view (``OUTRIDER-RUN.md``) of a governed run back into
  ``targets/<name>/``, without touching the operator's own notes.

This module deliberately does not import :mod:`outrider.cli` (the CLI imports it),
and reads/writes only the gitignored ``runs/`` and ``targets/`` trees.
"""
from __future__ import annotations

import mimetypes
import re
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import urlparse

from . import web_view
from .evidence import register_evidence, EvidenceRefusalError
from .state import load_manifest
from .workflow_guide import build_workflow_guide

DEFAULT_MAX_BYTES = 100 * 1024 * 1024
DEFAULT_ARTIFACT_TYPE = "legacy-import"
IMPORT_SUBDIR = "imported"
MATERIALIZED_FILENAME = "OUTRIDER-RUN.md"
GENERATED_BANNER = "<!-- GENERATED by `outrider materialize` — do not edit; regenerate instead. -->"

# Directories that never carry engagement evidence and only add noise/size.
_SKIP_DIR_NAMES = {".git", ".hg", ".svn", "__pycache__", ".venv", "venv", "node_modules", ".pytest_cache"}


def _iter_source_files(source: Path):
    """Yield ``(abs_path, posix_relpath, size)`` for regular files worth importing.

    Skips symlinks (anywhere in the path), well-known noise directories, and any
    entry that is not a regular file. Deterministically ordered.
    """
    for path in sorted(source.rglob("*")):
        rel = path.relative_to(source)
        if any(part in _SKIP_DIR_NAMES for part in rel.parts):
            continue
        # Reject a symlink at the leaf or any parent component under source.
        if any((source / PurePosixPath(*rel.parts[: i + 1])).is_symlink() for i in range(len(rel.parts))):
            continue
        if not path.is_file():
            continue
        try:
            size = path.stat().st_size
        except OSError:
            continue
        yield path, PurePosixPath(rel).as_posix(), size


def import_files_as_evidence(
    run_dir: str | Path,
    source_dir: str | Path,
    *,
    actor: str,
    artifact_type: str = DEFAULT_ARTIFACT_TYPE,
    max_bytes: int = DEFAULT_MAX_BYTES,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Copy ``source_dir`` files into ``run_dir/artifacts/imported`` and register
    each as evidence. Idempotent: files already registered are skipped. In
    ``dry_run`` mode nothing is written and ``run_dir`` is not touched."""
    run_dir = Path(run_dir)
    source_dir = Path(source_dir)
    dest_root = run_dir / "artifacts" / IMPORT_SUBDIR
    source_label = source_dir.name or "target"
    result = {"planned": [], "copied": 0, "registered": 0, "skipped_existing": 0, "skipped_large": 0, "dry_run": dry_run}

    for abs_path, rel, size in _iter_source_files(source_dir):
        if size > max_bytes:
            result["skipped_large"] += 1
            continue
        registry_path = f"artifacts/{IMPORT_SUBDIR}/{rel}"
        result["planned"].append(registry_path)
        if dry_run:
            continue
        dest = dest_root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.exists():
            dest.write_bytes(abs_path.read_bytes())
            result["copied"] += 1
        media = mimetypes.guess_type(dest.name)[0]
        try:
            register_evidence(
                run_dir, registry_path, actor, artifact_type,
                media_type=media, source=f"legacy-import:{source_label}",
                note="Imported from legacy target workspace",
            )
            result["registered"] += 1
        except EvidenceRefusalError as exc:
            if "already registered" in str(exc):
                result["skipped_existing"] += 1
            else:
                raise
    return result


def _rule_lines(rules: list[dict[str, Any]] | None) -> list[str]:
    if not rules:
        return ["- _none_"]
    return [f"- `{r.get('original')}`" for r in rules]


def render_run_markdown(run_dir: str | Path) -> str:
    """Render a governed run as a self-contained markdown working view. Read-only."""
    ov = web_view.run_overview(run_dir)
    guide = build_workflow_guide(run_dir, enrichment_enabled=False)
    sc = web_view.scope_view(run_dir)
    ev = web_view.evidence_view(run_dir)
    fv = web_view.finding_view(run_dir)

    out: list[str] = [GENERATED_BANNER, "", f"# Outrider engagement: {ov.get('target')}", ""]
    out += [
        "## Overview", "",
        f"- **Target:** {ov.get('target')}",
        f"- **Platform:** {ov.get('engagement_platform') or 'not configured'}",
        f"- **Phase:** {ov.get('phase_label') or ov.get('current_state')}",
        f"- **Health:** {ov.get('health', {}).get('status')}",
        f"- **Run ID:** {ov.get('run_id')}",
        f"- **Created:** {ov.get('created_at')}",
        f"- **Last activity:** {ov.get('last_transition_at') or ov.get('created_at')}",
        "",
    ]

    progress = guide.get("progress") or []
    if progress:
        out += ["## Progress", ""]
        out += [f"- {step.get('label')}: {step.get('status')}" for step in progress]
        out += [""]

    out += ["## Scope", "", "**In scope:**", ""]
    out += _rule_lines(sc.get("in_scope"))
    out += ["", "**Out of scope:**", ""]
    out += _rule_lines(sc.get("out_of_scope"))
    out += [""]

    records = ev.get("records") or []
    out += ["## Registered evidence", "", f"{ev.get('evidence_count', 0)} artifact(s).", ""]
    if records:
        out += ["| path | type | sha256 | size | verification |", "|---|---|---|---|---|"]
        for r in records:
            sha = (r.get("expected_sha256") or "")[:12]
            out.append(
                f"| `{r.get('relative_artifact_path')}` | {r.get('artifact_type')} | "
                f"`{sha}…` | {r.get('expected_size')} | {r.get('verification_status')} |"
            )
        out += [""]

    findings = fv.get("findings") or []
    out += ["## Promoted findings", "", f"{fv.get('finding_count', 0)} finding(s).", ""]
    if findings:
        for f in findings:
            out += [
                f"### {f.get('title')} ({f.get('severity')} / {f.get('confidence')})", "",
                f"- **Affected:** {f.get('affected_candidate')}",
                f"- **Location:** {f.get('location') or 'n/a'}",
                f"- **Impact:** {f.get('impact')}",
                f"- **Remediation:** {f.get('remediation')}",
                f"- **Promoted by:** {f.get('promoted_by')} at {f.get('promoted_at')}",
                f"- **Verification:** {f.get('current_verification', {}).get('overall_status')}",
                "",
            ]
    else:
        out += ["_No promoted findings. Findings are promoted only by a human reviewer._", ""]

    out += ["---", GENERATED_BANNER, ""]
    return "\n".join(out) + "\n"


def materialize_run(run_dir: str | Path, targets_root: str | Path, *, name: str, force: bool = False) -> Path:
    """Write ``targets_root/<name>/OUTRIDER-RUN.md`` from a governed run.

    Never overwrites a file of that name that was not generated by this function
    (detected via :data:`GENERATED_BANNER`) unless ``force`` is set — so the
    operator's own notes in the target folder are safe."""
    dest_dir = Path(targets_root) / name
    dest_dir.mkdir(parents=True, exist_ok=True)
    out = dest_dir / MATERIALIZED_FILENAME
    if out.exists() and not force:
        existing = out.read_text(encoding="utf-8", errors="replace")
        if GENERATED_BANNER not in existing:
            raise FileExistsError(
                f"{out} exists and was not generated by materialize; pass --force to overwrite"
            )
    out.write_text(render_run_markdown(run_dir), encoding="utf-8")
    return out


def resolve_run_dir(run_arg: str, runs_root: str | Path) -> Path | None:
    """Resolve a run argument that is either a run directory path or a run_id."""
    p = Path(run_arg)
    if p.is_dir() and (p / "manifest.json").is_file():
        return p
    try:
        return web_view._run_dir_for_id(runs_root, run_arg)
    except ValueError:
        return None


def default_run_name(run_dir: str | Path) -> str:
    """Directory-safe engagement name derived from the run's manifest target."""
    target = load_manifest(run_dir).target
    return target.strip().replace("https://", "").replace("http://", "").strip("/")


def resolve_import_source(base: str | Path, name: str) -> Path | None:
    """Resolve an import source directory strictly under ``base``.

    Used by the loopback portal so a browser can only import from subfolders of
    the configured targets base — never an absolute path, ``..`` traversal, or a
    symlink that escapes the base. Returns the real directory or ``None`` if the
    name is unsafe or does not resolve to a directory inside ``base``.
    """
    if not name or not isinstance(name, str):
        return None
    if name.startswith("/") or "\\" in name or "\x00" in name:
        return None
    parts = PurePosixPath(name).parts
    if not parts or any(p in ("", ".", "..") for p in parts):
        return None
    try:
        base_real = Path(base).resolve(strict=True)
    except OSError:
        return None
    candidate = base_real
    for part in parts:
        candidate = candidate / part
        try:
            if candidate.is_symlink():
                return None
        except OSError:
            return None
    try:
        real = candidate.resolve(strict=True)
    except OSError:
        return None
    try:
        real.relative_to(base_real)
    except ValueError:
        return None
    return real if real.is_dir() else None


_DOMAIN_RE = re.compile(r"([a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9-]+)+)", re.IGNORECASE)


def _memory_field(text: str, label: str) -> str | None:
    m = re.search(rf"^\*\*{re.escape(label)}:\*\*\s*(.+?)\s*$", text, re.MULTILINE | re.IGNORECASE)
    return m.group(1).strip() if m else None


def _asset_to_rule(cell: str) -> str | None:
    """Normalize one ``In-Scope Assets`` cell to a governed scope rule string.

    A URL is emitted as a scheme-agnostic ``host[:port][/path]`` rule (the scope
    engine now supports URL/path rules natively), so ``https://www.x.com/book/``
    yields ``www.x.com/book/`` and the exact path scope is preserved instead of
    being reduced to the bare host. Query strings and fragments are dropped (the
    scope engine rejects ``?``/``#``). A bare domain stays a domain rule. Returns
    ``None`` when no host can be found."""
    url = re.search(r"https?://[^\s)|\]]+", cell)
    if url:
        parsed = urlparse(url.group(0))
        host = (parsed.hostname or "").strip().lower().rstrip(".")
        if not host:
            return None
        rule = host
        try:
            if parsed.port is not None:
                rule = f"{host}:{parsed.port}"
        except ValueError:
            return None
        path = (parsed.path or "").rstrip()
        if path and path != "/":
            if not path.startswith("/"):
                path = "/" + path
            rule = rule + path
        return rule
    dm = _DOMAIN_RE.search(cell)
    if not dm:
        return None
    host = dm.group(1).strip().lower().rstrip(".")
    rule = host
    # A scheme-less asset may still carry a :port and/or /path right after the
    # host (e.g. ``api.x.com:8443/v1``); preserve them as a host:port/path rule.
    tail = re.match(r"(?::(\d{1,5}))?(/[^\s)|\]?#]*)?", cell[dm.end():])
    if tail:
        port_part, path_part = tail.group(1), tail.group(2)
        if port_part and 1 <= int(port_part) <= 65535:
            rule = f"{host}:{port_part}"
        if path_part and path_part != "/":
            rule = rule + path_part.rstrip().lower()
    return rule


def _rule_host(rule: str) -> str:
    """Bare host of a scope rule string (drops any ``/path`` and ``:port``)."""
    host = rule.split("/", 1)[0]
    return host.split(":", 1)[0]


def _parse_in_scope_assets(text: str) -> list[str]:
    """Extract explicit in-scope assets from the primary ## In-Scope Assets table
    only (stops at the next heading, so nuanced 'related domains' tables are not
    swept in as authorized scope). URL assets are emitted as ``host[/path]`` scope
    rules so the operator's exact path scope survives the import."""
    section = re.search(r"^##\s+In-?\s*Scope\s+Assets\s*$(.*?)(^#{2,}\s|\Z)", text, re.MULTILINE | re.IGNORECASE | re.DOTALL)
    if not section:
        return []
    out: list[str] = []
    seen: set[str] = set()
    for line in section.group(1).splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cell = line.strip("|").split("|")[0].strip()
        value = _asset_to_rule(cell)
        if value and value not in seen:
            seen.add(value)
            out.append(value[:512])
        if len(out) >= 50:
            break
    return out


def parse_target_memory(source_dir: str | Path) -> dict[str, Any]:
    """Best-effort extraction of engagement metadata from a legacy target's
    ``memory.md`` for prefilling the import form. Suggestions only — the operator
    reviews and confirms. Reads only ``memory.md``; never raises; returns just the
    fields it confidently finds."""
    try:
        mem = Path(source_dir) / "memory.md"
        if mem.is_symlink() or not mem.is_file():
            return {}
        text = mem.read_text(encoding="utf-8", errors="replace")[:200_000]
    except OSError:
        return {}
    result: dict[str, Any] = {}
    try:
        target_line = _memory_field(text, "Target")
        if target_line:
            paren = re.search(r"\(([^)]+)\)", target_line)
            dm = _DOMAIN_RE.search(paren.group(1)) if paren else None
            dm = dm or _DOMAIN_RE.search(target_line)
            if dm:
                result["target"] = dm.group(1).lower()[:253]
        program = _memory_field(text, "Program")
        if program:
            low = program.lower()
            result["engagement_platform"] = (
                "HackerOne" if "hackerone" in low else
                "Bugcrowd" if "bugcrowd" in low else
                "Internal assessment" if "internal" in low else
                "Client engagement" if "client" in low else
                "Other"
            )
            result["authorization_reference"] = program[:500]
        if "authorization_reference" not in result:
            msu = _memory_field(text, "Main Scope URL")
            if msu:
                result["authorization_reference"] = msu[:500]
        researcher = _memory_field(text, "Researcher")
        if researcher:
            result["actor"] = researcher.lstrip("@").strip()[:200]
        assets = _parse_in_scope_assets(text)
        if assets:
            result["in_scope"] = assets
            # The governed model requires the target host to be referenced by
            # scope (run_setup: "target is not allowed by scope"). A bare host is
            # in-scope by reachability if it is the host of some URL/domain rule,
            # so if the memory's Target line (often the apex) isn't among the
            # in-scope rule hosts, use the primary in-scope host — the target
            # stays a host, and the exact path scope is kept in the rules.
            hosts = [h for h in (_rule_host(a) for a in assets) if h]
            if result.get("target") not in hosts and hosts:
                result["target"] = hosts[0]
    except Exception:
        return result
    return result
