'use strict';
const state = { runs: [], selected: null };
const views = ['overview','scope','state','evidence','approvals','contracts','findings','integrity'];
const $ = (id) => document.getElementById(id);
function text(tag, value, cls){ const el=document.createElement(tag); if(cls) el.className=cls; el.textContent = value == null ? 'n/a' : String(value); return el; }
function clear(el){ while(el.firstChild) el.removeChild(el.firstChild); }
async function api(path){ const r=await fetch(path,{headers:{Accept:'application/json'}}); if(!r.ok) throw new Error('Request failed: '+r.status); return r.json(); }
function badge(v){ return text('span', v || 'unknown', 'badge '+(v||'')); }
function card(label,value){ const c=document.createElement('div'); c.className='card'; c.append(text('div',label,'muted'), text('strong',value)); return c; }
function renderSummary(runs){ const box=$('summary-cards'); clear(box); const by={}; runs.forEach(r=>{by[r.current_state||'unknown']=(by[r.current_state||'unknown']||0)+1}); box.append(card('Total runs',runs.length), card('Warnings',runs.filter(r=>r.health==='warning').length), card('Integrity errors',runs.filter(r=>r.health==='error').length)); Object.keys(by).sort().forEach(k=>box.append(card(k,by[k]))); }
function renderRuns(){ const q=$('filter-target').value.toLowerCase(); const st=$('filter-state').value; const h=$('filter-health').value; const list=$('run-list'); clear(list); const runs=state.runs.filter(r=>(!q||String(r.target||'').toLowerCase().includes(q))&&(!st||r.current_state===st)&&(!h||r.health===h)); $('empty-state').hidden = state.runs.length !== 0; runs.forEach(r=>{ const b=document.createElement('button'); b.className='run-card'; b.type='button'; b.append(text('h3',r.target||r.directory_name||'invalid run'), badge(r.current_state), badge(r.health), text('p',r.summary||'')); const meta=text('p',`Evidence ${r.evidence_count} · Active approvals ${r.active_approval_count} · Contracts ${r.request_count}/${r.result_count} · Findings ${r.finding_count}`,'muted'); b.append(meta); b.addEventListener('click',()=>selectRun(r.run_id)); if(r.run_id) list.append(b); }); }
async function loadRuns(){ try{ const data=await api('/api/runs'); state.runs=data.runs||[]; const states=[...new Set(state.runs.map(r=>r.current_state).filter(Boolean))].sort(); const sel=$('filter-state'); states.forEach(s=>sel.append(text('option',s))); renderSummary(state.runs); renderRuns(); $('loading').hidden=true; } catch(e){ $('loading').hidden=true; $('error-panel').hidden=false; $('error-panel').textContent='Unable to load runs.'; } }
function kv(obj){ const wrap=document.createElement('div'); wrap.className='grid'; Object.entries(obj||{}).forEach(([k,v])=>wrap.append(card(k, typeof v==='object' ? JSON.stringify(v) : v))); return wrap; }
function records(items){ const box=document.createElement('div'); if(!items||!items.length){ box.append(text('p','No records.','empty')); return box;} items.forEach(item=>{ const r=document.createElement('div'); r.className='record'; r.append(kv(item)); box.append(r); }); return box; }
function renderDetail(view,data){ const d=$('detail'); clear(d); d.append(text('h3',view[0].toUpperCase()+view.slice(1))); if(data.notice) d.append(text('p',data.notice,'banner')); if(data.errors&&data.errors.length) d.append(records(data.errors)); if(view==='overview') d.append(kv(data)); else if(view==='scope') d.append(kv(data.counts), text('h3','In scope'), records(data.in_scope), text('h3','Out of scope'), records(data.out_of_scope)); else if(view==='state') d.append(kv({valid:data.valid,current_state:data.current_state,event_count:data.event_count,last_transition_at:data.last_transition_at}), records(data.events)); else if(view==='evidence') d.append(kv({valid:data.valid,evidence_count:data.evidence_count}), records(data.records)); else if(view==='approvals') d.append(kv({valid:data.valid,approval_count:data.approval_count,active_count:data.active_count,expired_count:data.expired_count,revoked_count:data.revoked_count}), records(data.approvals)); else if(view==='contracts') d.append(kv({valid:data.valid,request_count:data.request_count,result_count:data.result_count}), text('h3','Requests'), records(data.requests), text('h3','Results'), records(data.results)); else if(view==='findings') d.append(kv({valid:data.valid,finding_count:data.finding_count}), records(data.findings)); else d.append(kv(data)); d.focus(); }
async function selectRun(id){ if(!id) return; state.selected=id; $('workspace').hidden=false; await loadDetail('overview'); }
async function loadDetail(view){ if(!state.selected) return; $('detail-loading').hidden=false; try{ renderDetail(view, await api(`/api/runs/${state.selected}/${view}`)); } catch(e){ clear($('detail')); $('detail').append(text('p','Unable to load this section.','error')); } finally{ $('detail-loading').hidden=true; } }
views.forEach(v=>document.addEventListener('click',e=>{ if(e.target && e.target.dataset && e.target.dataset.view===v) loadDetail(v); }));
['filter-target','filter-state','filter-health'].forEach(id=>document.addEventListener('input',e=>{ if(e.target&&e.target.id===id) renderRuns(); }));
loadRuns();
